import React, { useEffect, useState } from 'react';
import { resolveCanonicalTeamId } from '../sports/team-identity.js';
import { getLocalLogoPath, getRemoteLogoUrl } from '../sports/logo-registry.js';

const teamIdentity={
 'sac-kings':{label:'SAC',color:'#5A2D81'},'oregon-ducks':{label:'ORE',color:'#0A7A3B'},'kansas-state-wildcats':{label:'KSU',color:'#512888'},'washington-state-cougars':{label:'WSU',color:'#981E32'},'real-madrid':{label:'RMA',color:'#1F4E8C'},tottenham:{label:'TOT',color:'#132257'},'blue-jays':{label:'TOR',color:'#134A8E'},dodgers:{label:'LAD',color:'#005A9C'},oilers:{label:'EDM',color:'#FF4C00'},vikings:{label:'MIN',color:'#4F2683'},110:{label:'INT',color:'#00529B'}
};
const collegeAbbreviations={'Alabama Crimson Tide':'ALA','Arkansas Razorbacks':'ARK','Auburn Tigers':'AUB','Clemson Tigers':'CLEM','Florida Gators':'FLA','Florida State Seminoles':'FSU','Georgia Bulldogs':'UGA','Iowa Hawkeyes':'IOWA','LSU Tigers':'LSU','Miami Hurricanes':'MIA','Michigan Wolverines':'MICH','Mississippi State Bulldogs':'MSST','Notre Dame Fighting Irish':'ND','Ohio State Buckeyes':'OSU','Oklahoma Sooners':'OU','Oklahoma State Cowboys':'OKST','Ole Miss Rebels':'MISS','Oregon Ducks':'ORE','Kansas State Wildcats':'KSU','Washington State Cougars':'WSU','Penn State Nittany Lions':'PSU','South Carolina Gamecocks':'SC','Tennessee Volunteers':'TENN','Texas Longhorns':'TEX','Texas A&M Aggies':'TAMU','Utah Utes':'UTAH','Washington Huskies':'WASH','Wisconsin Badgers':'WIS'};
const collegeShortNames={'Oklahoma State Cowboys':'Oklahoma St.','Mississippi State Bulldogs':'Mississippi St.','Florida State Seminoles':'Florida St.','Kansas State Wildcats':'Kansas St.','Michigan State Spartans':'Michigan St.','Ohio State Buckeyes':'Ohio State','Penn State Nittany Lions':'Penn State','Arizona State Sun Devils':'Arizona St.','Iowa State Cyclones':'Iowa State','Boise State Broncos':'Boise St.','Oregon State Beavers':'Oregon St.','Washington State Cougars':'Washington St.'};
function normalizedName(name=''){return String(name).trim().replace(/\s+/g,' ');}
export function getTeamAbbreviation(team){const name=normalizedName(team?.name);const identity=teamIdentity[team?.id];if(identity)return identity.label;if(collegeAbbreviations[name])return collegeAbbreviations[name];const providerAbbr=normalizedName(team?.abbreviation);if(providerAbbr&&providerAbbr.length<=5&&providerAbbr!==name)return providerAbbr.toUpperCase();const words=name.replace(/[^a-zA-Z0-9 ]/g,'').split(' ').filter(Boolean);if(!words.length)return'TBD';return words.length===1?words[0].slice(0,4).toUpperCase():words.map((word)=>word[0]).join('').slice(0,4).toUpperCase();}
export function getDisplayTeamName(team){const name=normalizedName(team?.name)||'TBD';return collegeShortNames[name]||name;}
export function getTeamLogoSources(team){const canonicalId=resolveCanonicalTeamId(team);return {local:getLocalLogoPath({canonicalId,leagueId:team?.leagueId,providerId:team?.id,name:team?.name}),remote:getRemoteLogoUrl(team)};}
export function TeamMark({team,size='medium'}){const identity=teamIdentity[team?.id]||teamIdentity[resolveCanonicalTeamId(team)];const color=team?.color||team?.primaryColor||team?.teamColor||identity?.color||'#64748b';const label=getTeamAbbreviation(team);const {local,remote}=getTeamLogoSources(team);const [source,setSource]=useState(local||remote);useEffect(()=>{setSource(local||remote);},[local,remote]);const showLogo=Boolean(source);return <span className={`team-mark ${size} ${showLogo?'has-logo':''}`} style={{'--team-color':color}} aria-label={`${team?.name||'Team'} ${showLogo?'logo':'abbreviation'}`}>{showLogo?<img src={source} alt="" aria-hidden="true" loading="lazy" decoding="async" onError={()=>setSource((current)=>current===local?remote:null)}/>:<span>{label}</span>}</span>;}
