import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { leagues } from './sports/leagues.js';
import { favoriteTeamIds } from './sports/team-identity.js';
import { sanitizeGames } from './sports/data-reliability.js';
import { getGameStateRefreshDelay, mergeGameUpdate, mergeLiveGames } from './sports/live-state.js';
import { AppHeader } from './components/AppHeader.jsx';
import { CalendarView } from './components/CalendarView.jsx';
import { FilterSheet } from './components/FilterSheet.jsx';
import { GameDetailModal } from './components/GameDetailModal.jsx';
import { MyGamesView } from './components/MyGamesView.jsx';
import { ViewSwitcher } from './components/ViewSwitcher.jsx';
import './styles.css';
import './styles-polish.css';
import './theme-contrast.css';
import './spacing-refinement.css';
import './dark-heading-contrast.css';
import './watch-score-refinement.css';
import './premium-visual-system.css';
import './contrast-system.css';
import './skin-redesign.css';
import './skin-levelup.css';

const viewerTimeZone = Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC';
const CALENDAR_REFRESH_MS = 300_000;
function formatFreshness(date, loading) { if (loading && !date) return 'Updating data…'; if (!date) return 'Waiting for data'; const ageSeconds = Math.max(0, Math.floor((Date.now() - new Date(date).getTime()) / 1000)); if (ageSeconds < 10) return 'Updated just now'; if (ageSeconds < 60) return `Updated ${ageSeconds}s ago`; const minutes = Math.floor(ageSeconds / 60); if (ageSeconds < 120) return `Updated ${minutes}m ago`; return `Data delayed · ${minutes}m ago`; }
function localDateKey(date) { return new Intl.DateTimeFormat('en-CA', { timeZone: viewerTimeZone, year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date(date)); }
function mergeSelectedGame(current, liveGames) { if (!current) return current; const update = liveGames.find((game) => game.id === current.id); return update ? mergeGameUpdate(current, update) : current; }
function App() {
  const today = new Date(); const [view, setView] = useState('my-games'); const [cursor, setCursor] = useState(new Date(today.getFullYear(), today.getMonth(), today.getDate())); const [games, setGames] = useState([]); const gamesRef = useRef(games); gamesRef.current = games; const liveGamesRef = useRef(new Map()); const calendarRequestRef = useRef(0); const liveRequestRef = useRef(0); const liveAbortRef = useRef(null); const [activeLeagues, setActiveLeagues] = useState(leagues.map((league) => league.id)); const [favoritesOnly, setFavoritesOnly] = useState(false); const [filterOpen, setFilterOpen] = useState(false); const [selectedGame, setSelectedGame] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [dataHealth, setDataHealth] = useState(null); const [lastUpdated, setLastUpdated] = useState(null); const [freshnessNow, setFreshnessNow] = useState(() => Date.now());
  const loadGames = async ({ silent = false } = {}) => { const requestId = ++calendarRequestRef.current; if (!silent) setLoading(true); setError(''); try { const response = await fetch(`/api/sports?days=7&timezone=${encodeURIComponent(viewerTimeZone)}`, { cache: 'no-store' }); if (!response.ok) throw new Error('Sports data unavailable'); const payload = await response.json(); if (requestId !== calendarRequestRef.current) return; const nextGames = sanitizeGames(payload.games ?? []); const protectedLive = Array.from(liveGamesRef.current.values()); const mergedGames = mergeLiveGames(nextGames, protectedLive); setGames(mergedGames); setDataHealth(payload.health ?? null); setLastUpdated(payload.fetchedAt ?? new Date().toISOString()); setSelectedGame((current) => current ? mergedGames.find((game) => game.id === current.id) ?? current : current); } catch (err) { if (requestId === calendarRequestRef.current && (!silent || !gamesRef.current.length)) setError(err.message || 'Unable to load sports data'); } finally { if (requestId === calendarRequestRef.current && !silent) setLoading(false); } };
  const todayLeagueIds = useMemo(() => { const todayKey = localDateKey(Date.now()); const ids = new Set(); for (const game of games) if (localDateKey(game.startTime) === todayKey) ids.add(game.leagueId); return Array.from(ids).sort(); }, [games]); const todayLeagueQuery = todayLeagueIds.join(',');
  const loadLiveGames = async ({ silent = true } = {}) => { if (!todayLeagueQuery) return; const requestId = ++liveRequestRef.current; liveAbortRef.current?.abort(); const controller = new AbortController(); liveAbortRef.current = controller; try { const response = await fetch(`/api/sports?mode=live&leagues=${encodeURIComponent(todayLeagueQuery)}&timezone=${encodeURIComponent(viewerTimeZone)}`, { cache: 'no-store', signal: controller.signal }); if (!response.ok) throw new Error('Live sports data unavailable'); const payload = await response.json(); if (requestId !== liveRequestRef.current || controller.signal.aborted) return; const liveGames = sanitizeGames(payload.games ?? []); for (const game of liveGames) liveGamesRef.current.set(game.id, game); setGames((current) => mergeLiveGames(current, liveGames)); setSelectedGame((current) => mergeSelectedGame(current, liveGames)); setLastUpdated(payload.fetchedAt ?? new Date().toISOString()); } catch (err) { if (err?.name === 'AbortError') return; if (requestId === liveRequestRef.current && !silent) setError(err.message || 'Unable to load live sports data'); } finally { if (requestId === liveRequestRef.current && liveAbortRef.current === controller) liveAbortRef.current = null; } };
  useEffect(() => { void loadGames(); }, []); useEffect(() => { const timer = window.setInterval(() => { setFreshnessNow(Date.now()); void loadGames({ silent: true }); }, CALENDAR_REFRESH_MS); return () => window.clearInterval(timer); }, []); useEffect(() => { if (!todayLeagueQuery) return undefined; let cancelled = false; let timer; const scheduleNextLiveRefresh = () => { if (cancelled) return; const delay = getGameStateRefreshDelay(gamesRef.current); if (delay == null) return; timer = window.setTimeout(async () => { setFreshnessNow(Date.now()); await loadLiveGames(); scheduleNextLiveRefresh(); }, delay); }; void loadLiveGames(); scheduleNextLiveRefresh(); return () => { cancelled = true; if (timer) window.clearTimeout(timer); liveAbortRef.current?.abort(); }; }, [todayLeagueQuery]); useEffect(() => { const timer = window.setInterval(() => setFreshnessNow(Date.now()), 10_000); return () => window.clearInterval(timer); }, []);
  const filteredGames = useMemo(() => games.filter((game) => activeLeagues.includes(game.leagueId)).filter((game) => !favoritesOnly || favoriteTeamIds.has(game.homeTeamId) || favoriteTeamIds.has(game.awayTeamId)), [games, activeLeagues, favoritesOnly]); const toggleLeague = (id) => setActiveLeagues((prev) => prev.includes(id) ? prev.filter((item) => item !== id) : [...prev, id]); const shiftWeek = (delta) => setCursor((current) => new Date(current.getFullYear(), current.getMonth(), current.getDate() + (delta * 7))); const nflUnavailable = dataHealth?.nfl?.status === 'error'; const freshnessLabel = useMemo(() => formatFreshness(lastUpdated, loading), [lastUpdated, loading, freshnessNow]);
  return <main className="app-shell"><AppHeader loading={loading} onRefresh={loadGames} /><section className="page-intro"><div><span className="eyebrow">Personal sports intelligence</span><h1>GameDay</h1><p>One calendar. Every game ranked by competitive value, stakes, form, narrative, and what matters to you.</p></div><div className="window-note">7-day radar</div></section><ViewSwitcher view={view} onChange={setView} onFilter={() => setFilterOpen(true)} />{error && <div className="data-notice">{error}. Refresh to try again.</div>}{!error && nflUnavailable && <div className="data-notice">NFL data is temporarily unavailable. Other sports may still be current. Refresh to retry NFL data.</div>}{view === 'my-games' ? <MyGamesView games={filteredGames} now={today} onOpenGame={setSelectedGame} /> : <CalendarView games={filteredGames} cursor={cursor} onShiftWeek={shiftWeek} onOpenGame={setSelectedGame} />}<GameDetailModal game={selectedGame} onClose={() => setSelectedGame(null)} /><footer><span>{loading ? 'Loading sports data…' : `${filteredGames.length} games in your 7-day view`}</span><span className="data-freshness" title="Live polling is sport-aware: active games refresh aggressively, late-game states refresh faster, and halftime/intermissions back off. Upcoming games refresh more often near start time. The full calendar refreshes every 5 minutes.">{freshnessLabel}</span></footer><FilterSheet open={filterOpen} leagues={leagues} activeLeagues={activeLeagues} onToggleLeague={toggleLeague} favoritesOnly={favoritesOnly} onFavoritesOnly={setFavoritesOnly} onClose={() => setFilterOpen(false)} /><nav className="mobile-nav" aria-label="Primary navigation"><button className={view === 'my-games' ? 'active' : ''} onClick={() => setView('my-games')}>My Games</button><button className={view === 'calendar' ? 'active' : ''} onClick={() => setView('calendar')}>Calendar</button></nav></main>;
}
createRoot(document.getElementById('root')).render(<App />);
